### ISSUE TITLE
Artifacts stolen by nymphs can't be recovered if nymph is not killed before leaving level? (normal mode)

### ISSUE THREAD

**Issue by SilearFlare** [earlfogel/UltraRogue#5]
I don't know if this is actually a bug. 
I've managed to grab all the artifacts, but by DL90 a sorceress surrounded me with nymphs, who stole my scepter of might. 
![1591276395030](https://user-images.githubusercontent.com/5557920/83770911-f040ec00-a681-11ea-97d5-182f8e376393.png)
That would have been fine, if not for the fact she ran away while I was fighting yet another nymph who had stolen my junk, just in time for me to fall into a maze.
I got the wand of orcus and I thought the dungeon would stop at around 100. Instead, it fell into another maze and I kept going lower casting downstairs with the sil, hoping to eventually find the lost artifact lying on the ground like I used to before when losing them a floor above due to unforeseen circumstances.
50 levels after that, I gave up and let my @ get ravaged by Jubilex, realizing that I could never go upstairs. 
![RIP](https://user-images.githubusercontent.com/5557920/83771725-e075d780-a682-11ea-8410-943dd75abb45.png)

I thought that the artifacts not being able to respawn when lost/stolen was a hardmode only thing?

**Comment by earlfogel** [comment]
That is how it worked in the original game -- stolen artifacts could only be recovered by killing the thief, and even then it was hit and miss.  I thought I'd fixed this, but it turns out my fix didn't work below level 100.  So I've reworked that code again, and I believe this is resolved.

In theory the dungeon has an infinite number of levels, but the assumption is that you'll turn around and go back up once you have all the artifacts.

**Comment by SilearFlare** [comment]
That works for me! Thanks.
